Repository mqtt-tools/mqttwarn, pull requests merged in 2022-09, with the labels that each got.

#583 allow lwt alive/dead payload to configurable (defaults to "1"/"0")
  HANDBOOK.md
  mqttwarn/configuration.py
  mqttwarn/core.py
Labels: enhancement

#595 Add a bit of type hinting and basic `mypy` checks on `mqttwarn/core.py`
  mqttwarn/core.py
  mqttwarn/model.py
  pyproject.toml
  setup.py
Labels: quality

#589 Tests: Add e2e/system test cases to verify egress and ingress MQTT messages
  .github/workflows/tests.yml
  pyproject.toml
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/etc/status-publish.ini
  tests/test_core.py
  tests/test_e2e.py
  tests/util.py
Labels: enhancement, quality
